version: '3'

vars:
  LOCALES_DIR: "app/locales"
  TRANSLATION_LANGUAGES: ["en", "fr"]
  TRANSLATION_SOURCE_DIRS: ["app/api", "app/business"]

tasks:
  run-server:
    desc: "Run the uvicorn server"
    cmds:
      - uv run uvicorn app.main:app --reload

  tests:
    desc: "Run the tests"
    cmds:
      - uv run tox -vv

  translations-extract:
    desc: "Extract translatable strings from Python files into a .pot template"
    cmds:
      - find {{ .TRANSLATION_SOURCE_DIRS | join " " }} -name '*.py' | xargs xgettext --package-name="Suffering Footprint" --package-version="0.1.0" --from-code=UTF-8 -o {{ .LOCALES_DIR }}/messages.pot -L Python
      - python {{ .LOCALES_DIR }}/fix_pot_charset.py {{ .LOCALES_DIR }}/messages.pot
      - echo "✅ All strings extracted !"
    silent: true

  translations-update:
    desc: "Update .po files for all languages"
    cmds:
      - |
        for lang in {{ .TRANSLATION_LANGUAGES | join " " }}; do
          mkdir -p {{ .LOCALES_DIR }}/$lang/LC_MESSAGES
          if [ -f {{ .LOCALES_DIR }}/$lang/LC_MESSAGES/messages.po ]; then
              msgmerge --update {{ .LOCALES_DIR }}/$lang/LC_MESSAGES/messages.po {{ .LOCALES_DIR }}/messages.pot
          else
            msginit -l $lang -o {{ .LOCALES_DIR }}/$lang/LC_MESSAGES/messages.po -i {{ .LOCALES_DIR }}/messages.pot --no-translator
          fi
        done
      - echo "✅ All .po files updated !"
    silent: true

  translations-compile:
    desc: "Compile .po files into .mo files"
    cmds:
      - |
        for lang in {{ .TRANSLATION_LANGUAGES | join " " }}; do
          msgfmt -o {{ .LOCALES_DIR }}/$lang/LC_MESSAGES/messages.mo {{ .LOCALES_DIR }}/$lang/LC_MESSAGES/messages.po
        done
      - echo "✅ All .mo files compiled !"
    silent: true

  translations-all:
    desc: "Run all tasks: extract, update, and compile"
    cmds:
      - task: translations-extract
      - task: translations-update
      - task: translations-compile
