name: Backend tests

on:
  pull_request:
    paths:
      - 'backend/**'
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies with UV
        run: uv sync --all-groups

      # Install translation tools
      - name: Install gettext and babel
        run: |
          sudo apt-get install -y gettext
          uv pip install babel

      # Compile translations before running tests
      - name: Compile translations
        run: |
          # Compile using pybabel (more reliable path handling)
          pybabel compile -d app/locales

          # Ensure output exists for better debugging
          find app/locales -name "*.mo" | sort

      # Run tests with translation files available
      - name: Run tests
        run: uv run pytest tests/
